version: "3"
services:
  pilacoin-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=Mining
    ports:
      - "5432:5432"
  pilacoin-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - pilacoin-db